sudo: false
language: java
branches:
  only:
    - master
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"
deploy:
  provider: script
  script: "cp .m2/travis.settings.xml $HOME/.m2/settings.xml && mvn clean package deploy -Dregistry=https://maven.pkg.github.com/OnfireNetwork -Dtoken=$GH_TOKEN"
  skip_cleanup: true